
services:
  db:
    image: postgres:16-alpine
    container_name: riventa-db
    restart: unless-stopped
    env_file: .env
    ports:
      - "5432:5432"   # se conflitar, troque p/ "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 20

networks:
  default:
    name: riventa-net

volumes:
  db_data:
